config/routes.rb
Shop::Application.routes.draw do
  devise_for :users

  get "pages/index"

  get "pages/cart"

  get "pages/user"

  get "pages/cards"

  get "pages/flyers"

  get "pages/leaflets"

  get "pages/calendars"

  get "pages/posters"

  root :to => 'Pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def cart
  end

  def user
  end

  def cards
  end

  def flyers
  end

  def leaflets
  end

  def calendars
  end

  def posters
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container_12">
  <div class="grid_12">
    <ul>
      <li><%= link_to "Главная", root_path %></li>
      <li><%= link_to "Корзина", pages_cart_path %></li>
      <li><%= link_to "Профиль", edit_user_registration_path %></li>
    </ul>
  </div>

  <div class="grid_12">
    <%= yield %>
  </div>

  <div class="grid_12">
      Footer
  </div>
</div>
</body>
</html>

app/views/pages/calendars.html.erb
<h1>Pages#calendars</h1>
<p>Find me in app/views/pages/calendars.html.erb</p>

app/views/pages/cards.html.erb
<h1>Pages#cards</h1>
<p>Find me in app/views/pages/cards.html.erb</p>

app/views/pages/cart.html.erb
<h1>Pages#cart</h1>
<p>Find me in app/views/pages/cart.html.erb</p>

app/views/pages/flyers.html.erb
<h1>Pages#flyers</h1>
<p>Find me in app/views/pages/flyers.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/leaflets.html.erb
<h1>Pages#leaflets</h1>
<p>Find me in app/views/pages/leaflets.html.erb</p>

app/views/pages/posters.html.erb
<h1>Pages#posters</h1>
<p>Find me in app/views/pages/posters.html.erb</p>

app/views/pages/user.html.erb
<h1>Pages#user</h1>
<p>Find me in app/views/pages/user.html.erb</p>